server:
  port: 8080
spring:
  application:
    name: coupon
---

spring:
  profiles: default
  feign:
    hystrix:
      enabled: true
      
  hystrix:
    command:
      # 전역설정
      default:
        execution.isolation.thread.timeoutInMilliseconds: 3000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: coupon
          destination: mall
          contentType: application/json
        event-out:
          destination: mall
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url:
    ordering: localhost:8081


server:
  port: 8085

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: coupon
          destination: mall
          contentType: application/json
        event-out:
          destination: mall
          contentType: application/json

api:
  url:
    ordering: localhost:8080


